apiVersion: v1
kind: Pod
metaadata:
  name: myapp-pod
  # namespace: dev
  labels:
    app: myapp
    type: front-end
    location: us-east-1

spec:
  containers:
    - name: nginx-container
      image: nginx
