apiVersion: apps/v1
kind: ReplicaSet # case sensitive
metaadata:
  name: myapp-replicaset
  labels:
    app: myapp
    type: front-end

spec:
  template:
    metaadata:
      name: myapp-pod
      labels:
        app: myapp
        type: front-end
    spec:
      containers:
        - name: nginx-container
          image: nginx

  replicas: 6 # 3
  selector: 
    matchLabels:
      type: front-end # tier: front-end
